apiVersion: harness.io/v1
kind: Component
type: service
identifier: env_services_prod
name: env-services-prod
owner: group:account/HSF_Admins
orgIdentifier: default
projectIdentifier: technical_exercise
metadata:
  description: Services enabled in prod
  links:
    - title: Edit services
      url: https://loren.harness.io/ng/account/WqS38aeyQjayoqy6mzwceA/module/idp/create/templates/account.default.technical_exercise/services_update?formData=%7B%22repo%22%3A%22lorenyeung%2Fidp-env-services-demo-2%22%2C%22environment%22%3A%22prod%22%2C%22services%22%3A%5B%22gke%22%2C%22alloy_db%22%5D%7D
spec:
  lifecycle: experimental